---
# # build out the docker compose file here
- name: Create a directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /docker/homeserver
    - /docker/shared
    - /docker/organizr
    - /docker/sabnzbd
    - /docker/radarr
    - /docker/sonarr
    - /docker/ombi
    - /docker/hydra
    - /docker/jackett
    - /docker/nextcloud
    - /docker/tautulli

- name: touch docker-compose.yml
  file:
    path: /docker/homeserver/docker-compose.yml
    state: touch

- name: Build docker-compose
  blockinfile: 
    path: /docker/homeserver/docker-compose.yml
    block: |
       version: '3.4'
       services:
         organizr:
           container_name: organizr
           restart: always
           image: organizr/organizr
           volumes:
             - ${USERDIR}/organizr:/config
             - ${USERDIR}/shared:/shared
           ports:
             - "8090:80"
           environment:
             - PUID=${PUID}
             - PGID=${PGID}
             - TZ=${TZ}
         watchtower:
           container_name: watchtower
           restart: always
           image: v2tec/watchtower
           volumes:
             - /var/run/docker.sock:/var/run/docker.sock
           command: --schedule "0 0 4 * * *" --cleanup
         sabnzbd:
           image: "linuxserver/sabnzbd"
           container_name: "sabnzbd"
           volumes:
             - ${USERDIR}/sabnzbd:/config
             - /mnt/c3p0_data/downloads/completed:/downloads
             - /mnt/c3p0_data/downloads/incomplete:/incomplete-downloads
             - ${USERDIR}/shared:/shared
           ports:
               - "8091:8080"
           restart: always
           environment:
             - PUID=${PUID}
             - PGID=${PGID}
             - TZ=${TZ}  
         radarr:
           image: "linuxserver/radarr"
           container_name: "radarr"
           volumes:
             - ${USERDIR}/radarr:/config
             - /mnt/c3p0_data/downloads/completed:/downloads
             - /mnt/media/movies:/movies
             - "/etc/localtime:/etc/localtime:ro"
             - ${USERDIR}/shared:/shared
           ports:
             - "8092:7878"
           restart: always
           environment:
             - PUID=${PUID}
             - PGID=${PGID}
             - TZ=${TZ}
         sonarr:
           image: "linuxserver/sonarr"
           container_name: "sonarr"
           volumes:
             - ${USERDIR}/sonarr:/config
             - /mnt/c3p0_data/downloads/completed:/downloads
             - /mnt/media/tvshows:/tv
             - "/etc/localtime:/etc/localtime:ro"
             - ${USERDIR}/shared:/shared
           ports:
               - "8093:8989"
           restart: always
           environment:
             - PUID=${PUID}
             - PGID=${PGID}
             - TZ=${TZ}
         ombi:
           container_name: ombi
           restart: always
           image: linuxserver/ombi
           volumes:
             - ${USERDIR}/ombi:/config
             - ${USERDIR}/shared:/shared
           ports:
             - "8094:3579"
           environment:
             - PUID=${PUID}
             - PGID=${PGID}
             - TZ=${TZ}  
         hydra:
           image: "linuxserver/hydra"
           container_name: "hydra"
           volumes:
             - ${USERDIR}/hydra:/config
             - /mnt/c3p0_data/downloads:/downloads
             - ${USERDIR}/shared:/shared
           ports:
             - "8095:5075"
           restart: always
           environment:
             - PUID=${PUID}
             - PGID=${PGID}
             - TZ=${TZ} 
         jackett:
           image: "linuxserver/jackett"
           container_name: "jackett"
           volumes:
             - ${USERDIR}/jackett:/config
             - /mnt/c3p0_data/downloads/completed:/downloads
             - "/etc/localtime:/etc/localtime:ro"
             - ${USERDIR}/shared:/shared
           ports:
             - "8096:9117"
           restart: always
           environment:
             - PUID=${PUID}
             - PGID=${PGID}
             - TZ=${TZ}
         tautulli:
           container_name: tautulli
           restart: always
           image: linuxserver/tautulli
           volumes:
             - ${USERDIR}/tautulli/config:/config
             - ${USERDIR}/tautulli/logs:/logs:ro
             - ${USERDIR}/shared:/shared
           ports:
             - "8097:8181"
           environment:
             - PUID=${PUID}
             - PGID=${PGID}
             - TZ=${TZ}  
         nextcloud:
           container_name: nextcloud
           restart: always
           image: linuxserver/nextcloud
           volumes:
             - ${USERDIR}/nextcloud:/config
             - ${USERDIR}/shared_data:/data
             - ${USERDIR}/shared:/shared
           ports:
             - "8098:443"
           environment:
             - PUID=1000
             - PGID=1000

- name: homeserver docker-compose up
  docker_compose:
    project_src: /docker/homeserver/
    state: present
